sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t rpidocker/rpi-mono:4.6.1.3 -t rpidocker/rpi-mono:latest ./4.6.1.3/
  - docker build -t rpidocker/rpi-mono:4.6.1.3-onbuild -t rpidocker/rpi-mono:onbuild ./4.6.1.3/onbuild/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push rpidocker/rpi-mono;
    fi